### ISSUE TITLE
Show snackbar above bottom navigation

### ISSUE THREAD

**Issue by armpogart** [nstudio/nativescript-snackbar#1]
Any way to show snackbar above navigation and not on top of it?
For the bottom navigation following plugin is used (https://github.com/henrychavez/nativescript-bottom-navigation)

![Screenshot_HookApp_20190717-193134](https://user-images.githubusercontent.com/785768/61389330-c8119880-a8c9-11e9-86de-7961b0bdffcc.png)
![Screenshot_HookApp_20190717-193138](https://user-images.githubusercontent.com/785768/61389327-c7790200-a8c9-11e9-9743-cbacd7837767.png)

**Comment by bradmartin** [comment]
Try using the 'view' option and pass the instance of the bottom navigation and see if that works.
