### ISSUE TITLE
Error on call

### ISSUE THREAD

**Issue by ittrad-mobile-lab** [nstudio/nativescript-snackbar#12]
```
private successSnack() {
        const options: SnackBarOptions = {
            actionText: "Iti multumim pentru ajutor! ",
            actionTextColor: "#ff4081", // Optional, Android only
            snackText: "Doamne Ajuta! Ai castigat un cupon. Nu uita 12 cupoane = bilet la tombola.",
            textColor: "#346db2", // Optional, Android only
            hideDelay: 3500,
            backgroundColor: "#eaeaea", // Optional, Android only
            maxLines: 3, // Optional, Android Only
            isRTL: false // Optional, Android Only
            // view: <View>someView // Optional, Android Only, default to topmost().currentPage
        };

        snackBar.action(options).then((args) => {
            if (args.command === "Action") {
                // this.set('jsonResult', JSON.stringify(args));
                console.log(JSON.stringify(args));
            } else {
                // this.set('jsonResult', JSON.stringify(args));
                console.log("ACTION=", JSON.stringify(args));
            }
        });
    }
```

Unhandled Promise rejection: nativescript_snackbar__WEBPACK_IMPORTED_MODULE_7__.SnackBar is not a constructor ; Zone: <root> ; Task: Promise.then ; Value: TypeError: nativescript_snackbar__WEBPACK_IMPORTED_MODULE_7__.SnackBar is not a constructor TypeError: nativescript_snackbar__WEBPACK_IMPORTED_MODULE_7__.SnackBar is not a constructor
JS:     at file:///src/app/puzzle/puzzle.component.ts:374:49
JS:     at ZoneDelegate.push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke (file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:388:0)
JS:     at Zone.push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.Zone.run (file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:138:0)
JS:     at file:///node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:883:0
JS:     at ZoneDelegate.push.../node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invokeTask (file:///d...

**Comment by bradmartin** [comment]
Demo apps are functioning correctly. Check your usage, and perform a clean build of your project so that the node_modules are updated in the application binary on the device at install/run.
