### ISSUE TITLE
[NS 7][Angular 10] ReferenceError: NativeClass is not defined

### ISSUE THREAD

**Issue by jessorlisa** [nstudio/nativescript-snackbar#18]
**Environment**
 - CLI: 7.0.8
 - Cross-platform modules: 7.0.3
 - Android Runtime: 7.0.0
 - iOS Runtime: -
 - Angular CLI: 10.1.2
 - Angular: 10.1.2
 - Node: 12.18.3
 - @nativescript/angular: 10.1.0
 - **@nstudio/nativescript-snackbar: 2.0.0**

**Describe the bug**
`ns run android --no-hmr`results in the following error:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: ReferenceError: NativeClass is not defined
System.err: File: (file: node_modules/@nstudio/nativescript-snackbar/snackbar.android.js:178:0)
System.err: 
System.err: StackTrace: 
System.err: (file: node_modules/@nstudio/nativescript-snackbar/snackbar.android.js:178:0)
System.err: 	at ../node_modules/@nstudio/nativescript-snackbar/snackbar.js(file:///data/data/org.nativescript.testsnackbar/files/app/vendor.js:141899:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err: 	at ./app/item/items.component.ts(file: src/app/item/items.component.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err: 	at ./app/app-routing.module.ts(file: src/app/app-routing.module.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err: 	at ./app/app.module.ts(file: src/app/app.module.ts:1:0)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err: 	at (file: src/main.ts:1:106)
System.err: 	at ./main.ts(file:///data/data/org.nativescript.testsnackbar/files/app/bundle.js:344:30)
System.err: 	at __webpack_require__(file: src/webpack/bootstrap:74:0)
System.err: 	at checkDeferredModules(file: src/webpack/bootstrap:43:0)
System.err: 	at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
System.err: 	at (file:///data/data/org.nativescript.testsnackbar/files/app/bundle.js:2:57)
System.err: 	at require(:1:266)

```

**To Reproduce**
- Ensure latest nativescript (currently 7.0.8)
`npm -g install nativescript`
- Setup new Nativescript project (Angular flavour)
`ns create test-snackbar --ng`
`cd test-snackbar`
- Add plugin:
`ns plugin add @nstudio/nativescript-snackbar`
- Add import to src/app/item/items.component.ts
`import { SnackBar, SnackBarOptions } from "@nstudio/nativescript-snackbar";`
- Add the following to ngOnInit in src/app/item/items.component.ts
```
// Create an instance of SnackBar
const snackbar = new SnackBar();
snackbar.simple('Snackbar', 'red', '#fff', 3, false);
```
- Run on Android:
`ns run android --no-hmr`

**Expected behavior**
No error.

**Comment by bradmartin** [comment]
This would look like a bad publish on our part. I'll pull and push a bug release now.

**Comment by jessorlisa** [comment]
@bradmartin Wow - the fastest response ever! Thanks in advance.

**Comment by bradmartin** [comment]
Pull version `2.0.2` and it will work now. Thanks for reporting as I was rushing through plugins and forgot to apply the webpack `plugins` to the tsconfig to transpile the nativeclass down to ES5 for the runtimes 😄 so now it should be working.

**Comment by jessorlisa** [comment]
Now I get the following error (same setup as above):

```
JS: ERROR Error: Uncaught (in promise): Error: java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
JS: (file: node_modules/@nstudio/nativescript-snackbar/snackbar.android.js:37:0)
JS: 	at ZoneAwarePromise(file: node_modules/@nativescript/zone-js/zone-nativescript.js:902:0)
JS: 	at simple(file: node_modules/@nstudio/nativescript-snackbar/snackbar.android.js:26:0)
JS: 	at ngOnInit(file: src/app/item/items.component.ts:22:17)
JS: 	at callHook(file: node_modules/@angular/core/fesm2015/core.js:3038:0)
JS: 	at callHooks(file: node_modules/@angular/core/fesm2015/core.js:3008:0)
JS: 	at executeInitAndCheckHooks(file: node_modules/@angular/core/fesm2015/core.js:2960:0)
JS: 	at refreshView(file: node_modules/@angular/core/fesm2015/core.js:7178:0)
JS: 	at refreshEmbeddedViews(file: node_modules/@angular/core/fesm2015/core.js:8273:0)
JS: 	at refreshView(file:///d...
```

**Comment by bradmartin** [comment]
This could be timing related to when you're trying to present the snackbar, especially in an angular app. Is this on app startup? Would need to see more code of the app to be able to track that down.

**Comment by bradmartin** [comment]
![Screenshot_1600434535](https://user-images.githubusercontent.com/6006148/93601060-36e2f980-f986-11ea-887b-e38df920ca48.png)
![Screenshot_1600434533](https://user-images.githubusercontent.com/6006148/93601062-377b9000-f986-11ea-8b67-fd4820bd55ef.png)


Just took these screens from the `demo` app which is nativescript core, not angular and the snackbars appear to be working. So I'm guessing it's timing related or maybe a change needed in your application templates, but would need to see more to confirm.

**Comment by jessorlisa** [comment]
> This could be timing related to when you're trying to present the snackbar, especially in an angular app. Is this on app startup?

You are right, wrapping the test Snackbar in a timeout eliminates the error. So everything seems to be in order.

Thanks again!
