### ISSUE TITLE
I can't custom the position of a snackbar, it covers my bottom navigation, it would be great to place it a little bit higher from the bottom nabs

### ISSUE THREAD

**Issue by florianomanuel** [nstudio/nativescript-snackbar#21]
I'm using Nativescript Vue

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-04 at 13 53 35](https://user-images.githubusercontent.com/39900850/98109986-1b38a180-1ea7-11eb-9516-3f4677f96743.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-04 at 13 53 45](https://user-images.githubusercontent.com/39900850/98109992-1d026500-1ea7-11eb-924c-256aba258808.png)

<script>

import { SnackBar,SnackBarOptions } from '@nstudio/nativescript-snackbar';

export default {

    data()
    {... }

methods:{
showSnackbar() { 
   
    const snackbar = new SnackBar();
    
    snackbar
        .action({
           snackText:'View basket',
            textColor: 'white',
            actionTextColor: 'white',
            backgroundColor: '#212121',
            actionText: 'Total: R300',
            hideDelay: 350000,
            isRTL: true,
           // view: 
        })
        .then(result => console.log('Action Snackbar:', result)); 
},
}
}

Thanks for the great feedback

**Comment by bradmartin** [comment]
can you provide the XML or HTML of that layout?  Need that to be able to provide a solution for you :)

**Comment by florianomanuel** [comment]
> can you provide the XML or HTML of that layout? Need that to be able to provide a solution for you :)

<template>
    <Page >
       <ActionBar  class="Action-Bar">
         <GridLayout rows="*" columns="22,*,22" verticalAlignment="bottom">
             <Image  row="0" col="0" @tap="OpenHome()" src.decode="font://&#xf060;" class="fas t-36"></Image>
             <Label row="0" col="1" text="Drink Details"></Label>
            <Image  row="0" col="2" @tap="OpenCart()" src.decode="font://&#xf290;" class="fas t-36"></Image>
            <Label  v-show="cart.length>0" v-bind="size" class="badge" row="0" col="2" :text="size"  verticalAlignment="top" horizontalAlignment="right"></Label>
         </GridLayout>
       </ActionBar>

        <ScrollView orientation="verical">     
 
        <GridLayout rows="180,80,30,250,70," columns="*">

            <StackLayout height="80%" class="anim-images" row="0" >
                 <CardView class="card" elevation="40" radius="10" ios:shadowRadius="3" width="95%" >          
                    <GridLayout class="card-layout" rows="120,auto,auto" columns="auto,auto, *" >
                       <Image :src="item.image" stretch="aspectFit" colSpan="3" row="0" col="0"  />
                        <Label :text="item.price| dollars" class="price" row="0" col="0"  horizontalAlignment="left"  />
                        <label row="2" col="0" class="line"  :text="item.product_name"   />  
                        <label row="2" col="1" class="line" textWrap="true" :text="item.description"   />  
                        </GridLayout>
                      </CardView>
                        </StackLayout>
    
            <StackLayout row="1" >
                <CardView class="card_qty" elevation="40" radius="10" ios:shadowRadius="3" width="95%">
                    <GridLayout rows="*" columns="*,18,*">
                        <Button text="-" @tap="remove_qty()"  row="0" col="0" class="item_button" />
                        <label :text="item.qty" row="0" col="1" class="h2 text-center white"></label>
                         <Button text="+" @tap="add_qty()" row="0" col="2"  class="item_button"/> 
                    </GridLayout>
                </CardView>
            </StackLayout>

             <label  text="Similar Items" row="2"  class="line"></label>

            <ScrollView row="3" orientation="horizontal" scrollBarIndicatorVisible="false" paddingRight="15" >
                            
                            <StackLayout orientation="horizontal"  ref="bottom">

                                <GridLayout class="category" v-for="Items in $store.state.todo" :key="Items" width="170">

                                 <CardView class="card" elevation="40" radius="10" ios:shadowRadius="3"  height="220" width="150"   @tap="seeDetails(Items)">
                                            
                                    <GridLayout class="card-layout" rows="120,auto,auto,25" columns="*">
                                    <Image  class="img" :src="Items.image" stretch="aspectFit" col="0" row="0" />
                                    <Label :text="Items.product_name" class="h3 text-left" row="1" col="0" />
                                    <Label :text="Items.price" class="h3 text-left" row="2" col="0" />
                                    <Button row="3" col="0" text="Add" @tap="AddToCart(Items)" class="btn m-t-20 add-button" />
                                    
                                </GridLayout>
                                              
                                 </CardView>

                                </GridLayout>
                               
                               
                            </StackLayout>
            </ScrollView>

  <Button row="4" height="50"   text="Add to cart" @tap="AddToCart(item)" class="btn btn-primary m-t-20 add-button"  verticalAlignment="top" width="90%"  />
   

                     

        </GridLayout>
                  </ScrollView>

        
    </Page>
</template>

**Comment by florianomanuel** [comment]
> can you provide the XML or HTML of that layout? Need that to be able to provide a solution for you :)

```xml
    <Page >
       <ActionBar  class="Action-Bar">
         <GridLayout rows="*" columns="22,*,22" verticalAlignment="bottom">
             <Image  row="0" col="0" @tap="OpenHome()" src.decode="font://&#xf060;" class="fas t-36"></Image>
             <Label row="0" col="1" text="Drink Details"></Label>
            <Image  row="0" col="2" @tap="OpenCart()" src.decode="font://&#xf290;" class="fas t-36"></Image>
            <Label  v-show="cart.length>0" v-bind="size" class="badge" row="0" col="2" :text="size"  verticalAlignment="top" horizontalAlignment="right"></Label>
         </GridLayout>
       </ActionBar>

        <ScrollView orientation="verical">      
        <GridLayout rows="180,80,30,250,70," columns="*">

            <StackLayout height="80%" class="anim-images" row="0" >
                 <CardView class="card" elevation="40" radius="10" ios:shadowRadius="3" width="95%" >          
                    <GridLayout class="card-layout" rows="120,auto,auto" columns="auto,auto, *" >
                       <Image :src="item.image" stretch="aspectFit" colSpan="3" row="0" col="0"  />
                        <Label :text="item.price| dollars" class="price" row="0" col="0"  horizontalAlignment="left"  />
                        <label row="2" col="0" class="line"  :text="item.product_name"   />  
                        <label row="2" col="1" class="line" textWrap="true" :text="item.description"   />  
                        </GridLayout>
                      </CardView>
                        </StackLayout>
    
            <StackLayout row="1" >
                <CardView class="card_qty" elevation="40" radius="10" ios:shadowRadius="3" width="95%">
                    <GridLayout rows="*" columns="*,18,*">
                        <Button text="-" @tap="remove_qty()"  row="0" col="0" class="item_button" />
                        <label :text="item.qty" row="0" col="1" class="h2 text-center white"></label>
                         <Button text="+" @tap="add_qty()" row="0" col="2"  class="item_button"/> 
                    </GridLayout>
                </CardView>
            </StackLayout>

             <label  text="Similar Items" row="2"  class="line"></label>

            <ScrollView row="3" orientation="horizontal" scrollBarIndicatorVisible="false" paddingRight="15" >
                            
                            <StackLayout orientation="horizontal"  ref="bottom">

                                <GridLayout class="category" v-for="Items in $store.state.todo" :key="Items" width="170">

                                 <CardView class="card" elevation="40" radius="10" ios:shadowRadius="3"  height="220" width="150"   @tap="seeDetails(Items)">
                                            
                                    <GridLayout class="card-layout" rows="120,auto,auto,25" columns="*">
                                    <Image  class="img" :src="Items.image" stretch="aspectFit" col="0" row="0" />
                                    <Label :text="Items.product_name" class="h3 text-left" row="1" col="0" />
                                    <Label :text="Items.price" class="h3 text-left" row="2" col="0" />
                                    <Button row="3" col="0" text="Add" @tap="AddToCart(Items)" class="btn m-t-20 add-button" />
                                    
                                </GridLayout>
                                              
                                 </CardView>

                                </GridLayout>
                               
                               
                            </StackLayout>
            </ScrollView>

  <Button row="4" height="50"   text="Add to cart" @tap="AddToCart(item)" class="btn btn-primary m-t-20 add-button"  verticalAlignment="top" width="90%"  />
   

                     

        </GridLayout>
                  </ScrollView>

        
    </Page>
```

**Comment by bradmartin** [comment]
Thanks.

I would try setting an `id` on your parent `GridLayout`

like 
```xml
        <GridLayout id="mainGrid" rows="180,80,30,250,70," columns="*">
```

Then in your code you need to get that `View` and pass it to the snackbar calls.

So

```js

import { SnackBar,SnackBarOptions } from '@nstudio/nativescript-snackbar'; 
import { Frame } from '@nativescript/core';
export default { data() {... } 
methods:{ 
showSnackbar() { 
const snackbar = new SnackBar();
const grid = Frame.topmost().getViewById('mainGrid');
 snackbar .action({ 
snackText:'View basket', 
textColor: 'white', 
actionTextColor: 'white', 
backgroundColor: '#212121', 
actionText: 'Total: R300', 
hideDelay: 350000, 
isRTL: true, 
view: grid }).then(result => console.log('Action Snackbar:', result)); }, } }
```

This should anchor the snackbar on the grid and not the root android view of the entire activity.


Realized this is `vue` so you might have to do the `id` the way nativescript-vue does IDs and getting instances.

**Comment by florianomanuel** [comment]
> Thanks.
> 
> I would try setting an `id` on your parent `GridLayout`
> 
> like
> 
> ```
>         <GridLayout id="mainGrid" rows="180,80,30,250,70," columns="*">
> ```
> 
> Then in your code you need to get that `View` and pass it to the snackbar calls.
> 
> So
> 
> ```js
> import { SnackBar,SnackBarOptions } from '@nstudio/nativescript-snackbar'; 
> import { Frame } from '@nativescript/core';
> export default { data() {... } 
> methods:{ 
> showSnackbar() { 
> const snackbar = new SnackBar();
> const grid = Frame.topmost().getViewById('mainGrid');
>  snackbar .action({ 
> snackText:'View basket', 
> textColor: 'white', 
> actionTextColor: 'white', 
> backgroundColor: '#212121', 
> actionText: 'Total: R300', 
> hideDelay: 350000, 
> isRTL: true, 
> view: grid }).then(result => console.log('Action Snackbar:', result)); }, } }
> ```
> 
> This should anchor the snackbar on the grid and not the root android view of the entire activity.
> 
> Realized this is `vue` so you might have to do the `id` the way nativescript-vue does IDs and getting instances.

thank you very much brad.
