### ISSUE TITLE
[iOS] TTGSnackbar errors on last iOS and Nativescript versions

### ISSUE THREAD

**Issue by kriefsacha** [nstudio/nativescript-snackbar#48]
Hi, im on the last version of Nativescript angular (8.2.3), iOS 15.5, with the last version of the plugin, but i have errors when i build:

> Searching for devices...
> Preparing project...
> webpack is watching the files...
> assets by path assets/*.png 267 KiB 46 assets
> assets by path assets/sounds/ 1.7 MiB
>   asset assets/sounds/photoMessage.wav 304 KiB [emitted] [from: src/assets/sounds/photoMessage.wav] [copied]
>   + 7 assets
> assets by path *.js 20.4 MiB 3 assets
> assets by path fonts/*.ttf 361 KiB
>   asset fonts/fa-solid-900.ttf 198 KiB [emitted] [from: src/fonts/fa-solid-900.ttf] [copied]
>   + 2 assets
> assets by path assets/i18n/*.json 28.2 KiB
>   asset assets/i18n/he.json 10.2 KiB [emitted] [from: src/assets/i18n/he.json] [copied]
>   + 2 assets
> asset assets/NewNfc.jpeg 6.58 KiB [emitted] [from: src/assets/NewNfc.jpeg] [copied]
> asset assets/custom.css 2.43 KiB [emitted] [from: src/assets/custom.css] [copied]
> asset tns_modules/inspector_modules.js 1.22 KiB [emitted] (name: tns_modules/inspector_modules)
> Entrypoint bundle 20.4 MiB = runtime.js 88.4 KiB vendor.js 18.6 MiB bundle.js 1.63 MiB
> Entrypoint tns_modules/inspector_modules 18.7 MiB = runtime.js 88.4 KiB vendor.js 18.6 MiB tns_modules/inspector_modules.js 1.22 KiB
> runtime modules 25.4 KiB 13 modules
> orphan modules 576 bytes [orphan] 7 modules
> modules by path ./node_modules/ 6.37 MiB
>   javascript modules 6.1 MiB 656 modules
>   json modules 273 KiB
>     modules by path ./node_modules/mdn-data/css/*.json 242 KiB 3 modules
>     modules by path ./node_modules/css-tree/ 30.7 KiB 2 modules
> modules by path ./src/ 545 KiB
>   modules by path ./src/app/ 453 KiB 56 modules
>   modules by path ./src/*.ts 4.62 KiB 2 modules
>   modules by path ./src/*.css 87.2 KiB 2 modules
> external "~/package.json" 42 bytes [optional] [built] [code generated]
> fs (ignored) 15 bytes [built] [code generated]
> path (ignored) 15 bytes [built] [code generated]
> webpack 5.72.1 compiled successfully in 17509 ms
> Webpack compilation complete. Watching for file changes.
> (node:3957) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/metah.net/Documents/GitHub/visualy/VisualyScan/node_modules/tslib/package.json.
> Update this package.json to use a subpath pattern like "./*".
> (Use `node --trace-deprecation ...` to show where the warning was created)
> (node:3957) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/metah.net/Documents/GitHub/visualy/VisualyScan/node_modules/@nativescript/core/node_modules/tslib/package.json.
> Update this package.json to use a subpath pattern like "./*".
> (node:3957) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/metah.net/Documents/GitHub/visualy/VisualyScan/node_modules/@ngx-translate/core/node_modules/tslib/package.json.
> Update this package.json to use a subpath pattern like "./*".
> (node:3957) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/metah.net/Documents/GitHub/visualy/VisualyScan/node_modules/@ngx-translate/http-loader/node_modules/tslib/package.json.
> Update this package.json to use a subpath pattern like "./*".
> Installing pods...
> Analyzing dependencies
> Pre-downloading: `MaterialShowcase` from `https://github.com/shiv19/material-showcase-ios.git`, branch `nativescript`
> Pre-downloading: `QBImagePickerController` from `https://github.com/flypapertech/QBImagePicker.git`, commit `47aa21d32f8e6db0df79b089ad64e43d498b5951`
> Pre-downloading: `SwiftyCam` from `https://github.com/NathanWalker/SwiftyCam.git`, branch `feature/swift-4.2`
> Downloading dependencies
> Installing Firebase (9.1.0)
> Installing FirebaseAnalytics (9.1.0)
> Installing FirebaseAppCheckInterop (9.1.0)
> Installing FirebaseAuthInterop (9.1.0)
> Installing FirebaseCore (9.1.0)
> Installing FirebaseCoreDiagnostics (9.1.0)
> Installing FirebaseCoreExtension (9.1.0)
> Installing FirebaseCoreInternal (9.1.0)
> Installing FirebaseCrashlytics (9.1.0)
> Installing FirebaseDatabase (9.1.0)
> Installing FirebaseInstallations (9.1.0)
> Installing FirebaseStorage (9.1.0)
> Installing FirebaseStorageInternal (9.1.0)
> Installing GTMSessionFetcher (1.7.2)
> Installing GoogleAppMeasurement (9.1.0)
> Installing GoogleDataTransport (9.1.4)
> Installing GoogleMLKit (2.3.0)
> Installing GoogleToolboxForMac (2.3.2)
> Installing GoogleUtilities (7.7.0)
> Installing GoogleUtilitiesComponents (1.1.0)
> Installing MBProgressHUD (1.2.0)
> Installing MLImage (1.0.0-beta1)
> Installing MLKitBarcodeScanning (1.4.0)
> Installing MLKitCommon (3.1.0)
> Installing MLKitFaceDetection (1.3.0)
> Installing MLKitVision (1.3.0)
> Installing MaterialShowcase (0.6.5)
> Installing PromisesObjC (2.1.0)
> Installing Protobuf (3.20.1)
> Installing QBImagePickerController (3.4.0)
> Installing SwiftyCam (3.0.0)
> Installing SwiftyJSON (4.3.0)
> Installing TOCropViewController (2.5.0)
> Installing TTGSnackbar (1.11.1)
> Installing leveldb-library (1.22.1)
> Installing nanopb (2.30909.0)
> Generating Pods project
> Integrating client project
> 
> [!] Please close any current Xcode sessions and use `VisualyScan.xcworkspace` for this project from now on.
> Pod installation complete! There are 13 dependencies from the Podfile and 36 total pods installed.
> Updating runtime package.json with configuration values...
> Project successfully prepared (ios)
> Building project...
> Xcode build...
> 2022-06-12 18:18:30.851 xcodebuild[4119:30262] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
> 2022-06-12 18:18:30.851 xcodebuild[4119:30262] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
> 2022-06-12 18:18:31.865 xcodebuild[4119:30320]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
> Details:  (null) deviceType from da54f39207cc0db0dc8f47b198c2ad57b761f109 was NULL when -platform called.
> Object:   <DTDKMobileDeviceToken: 0x7f9757e78c80>
> Method:   -platform
> Thread:   <NSThread: 0x60000381df40>{number = 3, name = (null)}
> Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
> 2022-06-12 18:18:32.011 xcodebuild[4119:30312]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
> Details:  (null) deviceType from da54f39207cc0db0dc8f47b198c2ad57b761f109 was NULL when -platform called.
> Object:   <DTDKMobileDeviceToken: 0x7f9757e78c80>
> Method:   -platform
> Thread:   <NSThread: 0x60000371ca80>{number = 7, name = (null)}
> Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
> 2022-06-12 18:18:32.072 xcodebuild[4119:30312]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-20038/DTDeviceKitBase/DTDKRemoteDeviceData.m:373
> Details:  (null) deviceType from da54f39207cc0db0dc8f47b198c2ad57b761f109 was NULL when -platform called.
> Object:   <DTDKMobileDeviceToken: 0x7f9757e78c80>
> Method:   -platform
> Thread:   <NSThread: 0x60000371ca80>{number = 7, name = (null)}
> Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:386:42: error: 'style' has been renamed to 'activityIndicatorViewStyle'
>             return activityIndicatorView.style
>                                          ^~~~~
>                                          activityIndicatorViewStyle
> UIKit.UIActivityIndicatorView:10:14: note: 'style' was introduced in Swift 4.2
>     open var style: UIActivityIndicatorViewStyle { get set }
>              ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:389:35: error: 'style' has been renamed to 'activityIndicatorViewStyle'
>             activityIndicatorView.style = newValue
>                                   ^~~~~
>                                   activityIndicatorViewStyle
> UIKit.UIActivityIndicatorView:10:14: note: 'style' was introduced in Swift 4.2
>     open var style: UIActivityIndicatorViewStyle { get set }
>              ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:563:51: error: 'common' has been renamed to 'RunLoopMode.commonModes'
>         RunLoop.main.add(dismissTimer!, forMode: .common)
>                                                   ^~~~~~
>                                                   RunLoopMode.commonModes
> Foundation.RunLoop.Mode:9:23: note: 'common' was introduced in Swift 4.2
>     public static let common: RunLoopMode
>                       ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:673:51: error: type 'UIAccessibilityNotifications' (aka 'UInt32') has no member 'announcement'
>               UIAccessibility.post(notification: .announcement, argument: self.message)
>                                                  ~^~~~~~~~~~~~
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:860:63: error: 'orientationDidChangeNotification' has been renamed to 'NSNotification.Name.UIDeviceOrientationDidChange'
>                                                name: UIDevice.orientationDidChangeNotification, object: nil)
>                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                               NSNotification.Name.UIDeviceOrientationDidChange
> UIKit.UIDevice:3:22: note: 'orientationDidChangeNotification' was introduced in Swift 4.2
>     public class let orientationDidChangeNotification: NSNotification.Name
>                      ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:862:66: error: 'keyboardWillShowNotification' has been renamed to 'NSNotification.Name.UIKeyboardWillShow'
>                                                name: UIResponder.keyboardWillShowNotification, object: nil)
>                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                                  NSNotification.Name.UIKeyboardWillShow
> UIKit.UIResponder:3:22: note: 'keyboardWillShowNotification' was introduced in Swift 4.2
>     public class let keyboardWillShowNotification: NSNotification.Name
>                      ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:864:66: error: 'keyboardWillHideNotification' has been renamed to 'NSNotification.Name.UIKeyboardWillHide'
>                                                name: UIResponder.keyboardWillHideNotification, object: nil)
>                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                                  NSNotification.Name.UIKeyboardWillHide
> UIKit.UIResponder:7:22: note: 'keyboardWillHideNotification' was introduced in Swift 4.2
>     public class let keyboardWillHideNotification: NSNotification.Name
>                      ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:937:37: error: 'init(style:)' has been renamed to 'init(activityIndicatorStyle:)'
>         let activityIndicatorView = UIActivityIndicatorView(style: .white)
>                                     ^                       ~~~~~
>                                                             activityIndicatorStyle
> UIKit.UIActivityIndicatorView:5:12: note: 'init(style:)' was introduced in Swift 4.2
>     public init(style: UIActivityIndicatorViewStyle)
>            ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:1110:71: error: 'keyboardFrameEndUserInfoKey' has been renamed to 'UIKeyboardFrameEndUserInfoKey'
>         guard let keyboardFrame = notification?.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue else {
>                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                                                       UIKeyboardFrameEndUserInfoKey
> UIKit.UIResponder:15:22: note: 'keyboardFrameEndUserInfoKey' was introduced in Swift 4.2
>     public class let keyboardFrameEndUserInfoKey: String
>                      ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:1151:32: error: 'inset(by:)' has been renamed to 'UIEdgeInsetsInsetRect(_:_:)'
>         let insetRect = bounds.inset(by: contentInset)
>                                ^~~~~
>                                UIEdgeInsetsInsetRect
> UIKit.CGRect:3:17: note: 'inset(by:)' was introduced in Swift 4.2
>     public func inset(by insets: UIEdgeInsets) -> CGRect
>                 ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:1158:25: error: 'inset(by:)' has been renamed to 'UIEdgeInsetsInsetRect(_:_:)'
>         return textRect.inset(by: invertedInsets)
>                         ^~~~~
>                         UIEdgeInsetsInsetRect
> UIKit.CGRect:3:17: note: 'inset(by:)' was introduced in Swift 4.2
>     public func inset(by insets: UIEdgeInsets) -> CGRect
>                 ^
> /Users/metah.net/Documents/GitHub/visualy/VisualyScan/platforms/ios/Pods/TTGSnackbar/TTGSnackbar/TTGSnackbar.swift:1162:33: error: 'inset(by:)' has been renamed to 'UIEdgeInsetsInsetRect(_:_:)'
>         super.drawText(in: rect.inset(by: contentInset))
>                                 ^~~~~
>                                 UIEdgeInsetsInsetRect
> UIKit.CGRect:3:17: note: 'inset(by:)' was introduced in Swift 4.2
>     public func inset(by insets: UIEdgeInsets) -> CGRect
>                 ^
> Command CompileSwiftSources failed with a nonzero exit code
> remark: Incremental compilation has been disabled: is not currently compatible with embedding LLVM IR bitcode
> Command CompileSwiftSources failed with a nonzero exit code
> note: Using new build system
> note: Planning
> note: Build preparation complete
> note: Building targets in dependency order
> ** ARCHIVE FAILED **
> 
> Unable to apply changes on device: da54f39207cc0db0dc8f47b198c2ad57b761f109. Error is: Command xcodebuild failed with exit code 65.

It seems like some stuff changed in TTGSnackbar.

package.json:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/forms": "~13.2.0",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@nativescript-community/ui-pulltorefresh": "^2.5.1",
    "@nativescript/angular": "^13.0.0",
    "@nativescript/background-http": "~5.0.0",
    "@nativescript/camera": "^5.0.12",
    "@nativescript/core": "^8.2.3",
    "@nativescript/datetimepicker": "2.1.9",
    "@nativescript/firebase-core": "^2.0.2",
    "@nativescript/firebase-crashlytics": "^2.0.2",
    "@nativescript/firebase-database": "^2.0.2",
    "@nativescript/firebase-storage": "^2.0.2",
    "@nativescript/geolocation": "~8.0.0",
    "@nativescript/imagepicker": "~1.0.0",
    "@nativescript/mlkit-barcode-scanning": "^1.0.5",
    "@nativescript/mlkit-core": "^1.0.5",
    "@nativescript/mlkit-face-detection": "^1.0.5",
    "@nativescript/theme": "^3.0.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@nstudio/nativescript-camera-plus": "^4.1.0",
    "@nstudio/nativescript-loading-indicator": "^4.1.2",
    "@nstudio/nativescript-snackbar": "^2.1.0",
    "crypto-browserify": "^3.12.0",
    "latest": "^0.2.0",
    "nativescript-app-tour": "^4.0.0",
    "nativescript-imagecropper": "~4.0.0",
    "nativescript-nfc": "~5.0.0",
    "nativescript-permissions": "^1.3.8",
    "nativescript-sound-kak": "^1.2.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-chart": "~9.0.0",
    "nativescript-ui-sidedrawer": "~10.0.0",
    "nativescript-webview-interface": "^1.4.2",
    "rxjs": "^7.4.0",
    "stream-browserify": "^3.0.0",
    "tns-platform-declarations": "^6.5.15",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^13.3.6",
    "@angular-eslint/builder": "13.0.1",
    "@angular-eslint/eslint-plugin": "13.0.1",
    "@angular-eslint/eslint-plugin-template": "13.0.1",
    "@angular-eslint/schematics": "13.0.1",
    "@angular-eslint/template-parser": "13.0.1",
    "@angular/compiler-cli": "~13.2.0",
    "@nativescript/android": "8.2.3",
    "@nativescript/ios": "8.2.3",
    "@nativescript/schematics": "^0.5.2",
    "@nativescript/types": "~8.2.0",
    "@nativescript/webpack": "~5.0.0",
    "@ngtools/webpack": "~13.2.0",
    "@types/jasmine": "^3.5.11",
    "@typescript-eslint/eslint-plugin": "5.3.0",
    "@typescript-eslint/parser": "5.3.0",
    "eslint": "^8.2.0",
    "typescript": "~4.5.5"
  },
  "readme": "NativeScript Application",
  "main": "./src/main.ts",
  "scripts": {
    "lint": "ng lint"
  }
}
```

I hope i gave you all the informations you need.
If you could take a look @bradmartin @NathanWalker i would be glad, this is a very useful library.. thank you for everything !

**Comment by kriefsacha** [comment]
@bradmartin @NathanWalker no one can help with this please ? Very important. Thank you very much

**Comment by bradmartin** [comment]
Hi @kriefsacha - I'm not entirely sure what is causing this to happen during your build. I will try to clear some time to try the demo app out in a day or two and see if it works. If you have time, you could try cloning this repo, build the plugin, and run the demo app to see if it archives or not. That would be good to know and help rule out some things.

**Comment by kriefsacha** [comment]
Hi @bradmartin thank you for your response, i don't have any problem with helping. The only thing that i didnt understand is when you say build the plugin. How am i suppose to do that ? Sorry i never done that

**UPDATE**

Never mind i found your countributing doc, im doing that now

**Comment by kriefsacha** [comment]
@bradmartin I got a different error by doing what you told me:

> ERROR in Symbol ListViewComponent declared in /Users/metah.net/Documents/GitHub/nativescript-snackbar/demo-angular/node_modules/@nativescript/angular/directives/list-view-comp.d.ts is not exported from @nativescript/angular/nativescript.module (import into /Users/metah.net/Documents/GitHub/nativescript-snackbar/demo-angular/src/app/item/item-detail.component.ts)

Which is not the same with what I had

**Comment by kriefsacha** [comment]
Okay some news @bradmartin , I had to make some changes like changing from `'@nativescript/angular/router'` to `'@nativescript/angular' `, from `'@nativescript/angular/nativescript.module'` to `'@nativescript/angular'` , `'@nativescript/angular/platform'` to `'@nativescript/angular'` .

But after those changes, I succeeded to make it build, but not run.

I keep having this error now:

> CONSOLE LOG: Angular is running in development mode. Call enableProdMode() to enable production mode.
> ***** Fatal JavaScript exception - application has been terminated. *****
> NativeScript encountered a fatal error: Uncaught Error: Root should be either UIViewController or UIView
> at
> ZoneAwareError(file: node_modules/@nativescript/zone-js/zone-nativescript.js:1298:0)
> at setViewControllerView(file: node_modules/@nativescript/core/application/index.ios.js:417:0)
> at setWindowContent(file: node_modules/@nativescript/core/application/index.ios.js:258:0)
> at notifyAppStarted(file: node_modules/@nativescript/core/application/index.ios.js:165:0)
> at didFinishLaunchingWithOptions(file: node_modules/@nativescript/core/application/index.ios.js:149:0)
> at push.../node_modules/@nativescript/core/application/index.js.NotificationObserver.onReceive(file: node_modules/@nativescript/core/application/index.ios.js:39:0)
> *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught Error: Root should be either UIViewController or UIView
> at
> ZoneAwareError(file: node_modules/@nativescript/zone-js/zone-nativescript.js:1298:0)
> at setViewControllerView(file: node_modules/@nativescript/core/application/index.ios.js:417:0)
> at setWindowContent(file: node_modules/@nativescript/core/application/index.ios.js:258:0)
> at notifyAppStarted(file: node_modules/@nativescript/core/application/index.ios.js:165:0)
> at didFinishLaunchingWithOptions(file: node_modules/@nativescript/core/application/index.ios.js:149:0)
> at push.../node_modules/@nativescript/core/application/index.js.NotificationObserver.onReceive(file: node_modules/@nativescript/core/application/index.ios.js:39:0)
> ', reason: '(null)'
> *** First throw call stack:
> (0x180493d0c 0x197c84ee4 0x10118bb70 0x10150a968 0x10150a7d4 0x10144b53c 0x1013a3d28 0x1013a32dc 0x1011f6780 0x1010cff90 0x1011c1264 0x1011c41b4 0x18042a2d8 0x1804bf8d4 0x180494bf4 0x18043f060 0x181b2f05c 0x182c17878 0x182c00e28 0x182a6ed24 0x1828d5cf0 0x1829f85ec 0x182b0d994 0x182d35dd0 0x182cc5b38 0x1828d6a3c 0x18299250c 0x1828d87cc 0x1829bcd44 0x182e129c0 0x182906474 0x1829480f4 0x182a7378c 0x1829b<\M-b\M^@\M-&>

But for some reason my app wouldn't even build. Errors about TTGSnackbar.. if you could help I would be very glad, this is a very good plugin

**Comment by kriefsacha** [comment]
@bradmartin dont forget to take a look when you can please

**Comment by kriefsacha** [comment]
@bradmartin did you have time to check please ?

**Comment by kriefsacha** [comment]
Okay so i had to put that it compile with swift 5... it was by default with swift 4.. now i have problems with other plugins. Thank you
