### ISSUE TITLE
iOS hideDelay property does not work anymore since v.1.1.0

### ISSUE THREAD

**Issue by felixkrautschuk** [nstudio/nativescript-snackbar#6]
The `hideDely` property does not have any effect on iOS anymore, the SnackBar disappears after short time, no matter what you define in the options.

This issue can be reproduced using the demo app, just set the hideDelay to 9000, the Snackbar is hidden after about 3 seconds.

**Comment by yassern** [comment]
the new swift library don't have this options yet, but we can `await a setTimeout` manually or use a `rxjs debounceTime` internally on our plugin

**Comment by bradmartin** [comment]
I'm good with whatever works @yassern if you want to help with this one since you're most familiar with the iOS side at the moment 👍

**Comment by yassern** [comment]
ops, the library has a `duration` property, i see it now, i will make a PR ASAP.
before do that i have a question, the `hideDelay` option is only on `snackbar.action`, that behaviour is correct?

**Comment by bradmartin** [comment]
Yea as of now it's only on `action`. So that's fine, we can improve `simple` later and actually make it accept an `object` to allow similar custom options for both `simple` and `action` but if you wanna keep it simple for now that's fine 👍

**Comment by felixkrautschuk** [comment]
@bradmartin @yassern thanks for the fast fix 👍
